[project]
name = "authenticate-backrun"
authors = ["Web3 Security Team"]
description = "Secure backrun authentication and escrow protocol"
telemetry = false
requirements = []
[contracts.backrun-escrow]
path = "contracts/backrun-escrow.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
